name: meson

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  meson-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux GCC 12,         os: ubuntu-latest,  compiler: g++12,    cxx: "g++-12",     backend: "ninja",          build: "linux-libstdc++", args: ""}
        - { name: Linux GCC 12 nounity, os: ubuntu-latest,  compiler: g++12,    cxx: "g++-12",     backend: "ninja",          build: "linux-libstdc++", args: "-Dunity_build=false"}
        - { name: Linux GCC 12 shared,  os: ubuntu-latest,  compiler: g++12,    cxx: "g++-12",     backend: "ninja",          build: "linux-libstdc++", args: "--default-library shared"}
        - { name: Linux Clang 15,       os: ubuntu-latest,  compiler: clang-15, cxx: "clang++-15", backend: "ninja",          build: "linux-libc++", args: ""}
        - { name: Windows 64,           os: windows-latest, compiler: msvc,     cxx: "cl",         backend: "vs2022 --vsenv", build: "win64-vs2022", args: ""}
        - { name: MacOS,                os: macos-latest,   compiler: clang++,  cxx: "clang++",    backend: "ninja",          build: "osx-libc++", args: ""}
        build-type:
        - release

    name: ${{matrix.platform.name}} ${{matrix.build-type}} ${{matrix.config.name}}
    runs-on: ${{matrix.platform.os}}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - name: meson setup
      run: CXX=${{matrix.platform.cxx}} meson setup ${{matrix.platform.build}} --backend=${{matrix.platform.backend}} -Dbuildtype=${{matrix.build-type}} -Dprefix=`pwd`/../install ${{matrix.platform.args}}

    - name: Build
      run: meson compile -C ${{matrix.platform.build}}

    - name: Install
      run: meson install -C ${{matrix.platform.build}}

    - name: Test single header
      run: meson test -C ${{matrix.platform.build}}
